version: "3.9"

services:
  db:
    image: postgres:16
    container_name: ev3crewai-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agents_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - crewai-net

  backend:
    container_name: ev3crewai-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - FRONTEND_BASE_URL=${FRONTEND_BASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
      - MAIL_SERVER=${MAIL_SERVER:-smtp.sendgrid.net}
      - MAIL_PORT=${MAIL_PORT:-587}
      - MAIL_USE_TLS=${MAIL_USE_TLS:-true}
    expose:
      - "5000"
    depends_on:
      - db
    networks:
      - crewai-net

  nginx:
    image: nginx:latest
    container_name: ev3crewai-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - crewai-net

volumes:
  pgdata:

networks:
  crewai-net:
    driver: bridge
