version: "3.9"

services:
  backend:
    build: .
    container_name: ev3crewai-backend
    expose:
      - "5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
    command: python manage.py run --host=0.0.0.0 --port=5000
    networks:
      - app-network

  nginx:
    image: nginx:1.18
    container_name: ev3crewai-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

